# -*- coding: utf-8 -*-
"""LaboratórioMedicaoExperimentacaoSprint2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ky6RzhMIunIm8DChPd0t0IGTmeBoj2R
"""

import requests
import json
import pandas as pd

url = 'https://api.github.com/graphql'

headers = {'Authorization': 'bearer 73af344f4d09bd6552ba2a68c80981a4146328a2'}

query = """query estrelas {
  search(type: REPOSITORY, first: 10, after: {AFTER}, query: "stars:=>0") {
    pageInfo{      
      endCursor
    }
    nodes {
      ... on Repository {
        nome: nameWithOwner
        numeroEstrelas: stargazerCount
        dataCriacao: createdAt
        linguagemPrimaria: primaryLanguage {
          name
        }
        quantidadePullRequests: pullRequests(states: MERGED) {
          totalCount
        }
        quantidadeReleases: releases {
          totalCount
        }
        dataUltimaRelease: latestRelease {
          createdAt
        }
        totalOpenIssues: issues(states: CLOSED) {
          totalCount
        }
        totalIssues: issues {
          totalCount
        }
      }
    }
  }
}"""


def executar_requisicao(url, query, header): 
    print(query)
    request = requests.post(url, json={'query': query}, headers=header)

    if request.status_code == 200:
        return request.json()
    else:
        raise Exception("falha na requisição com código {}. {}".format(request.status_code, query))

after = 'null'
resposta = executar_requisicao(url, query.replace('{AFTER}', after), headers)
after = '"' + resposta['data']['search']['pageInfo']['endCursor'] + '"'

for i in range(99):
  aux = executar_requisicao(url, query.replace('{AFTER}', after), headers)
  after = '"' + aux['data']['search']['pageInfo']['endCursor'] + '"'
  resposta.update(aux)

#criando arquivo .json, lendo e convertendo para Excel.
with open('resposta.json', 'w') as f:
    json.dump(resposta, f)

df = pd.read_json('resposta.json')
df.to_excel('resposta.xls')